const CarList = [
  {
    id: 1,
    name: "Nissan Magnite",
    year: 2023,
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    rating: 5.0,
    reviews: 6,
    distance: 9.7,
    location:
      "PLOT NO-5, G-2, GROUND FLOOR, CITY CENTRE MALL, CITY CENTER MALL, NEAR HALDIRAM, Pocket 7, Sector 12 Dwarka, Dwarka, New Delhi, Delhi, 110075, India",
    price: 3500,
    baseDeliveryFee: 350,
    deliveryPerKm: 19,
    features: [
      "Bluetooth",
      "AC",
      "AUX",
      "GPS Navigation",
      "Sunroof",
      "Airbags",
    ],
    images: [
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
    ],
  },
  {
    id: 2,
    name: "Honda City",
    year: 2022,
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    rating: 4.8,
    reviews: 15,
    distance: 5.2,
    location: "Connaught Place, New Delhi, Delhi, 110001, India",
    price: 4200,
    baseDeliveryFee: 350,
    deliveryPerKm: 19,
    features: ["Apple CarPlay", "Android Auto", "Sunroof", "Leather Seats"],
    images: [
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
    ],
  },
  {
    id: 3,
    name: "Hyundai Creta",
    year: 2023,
    transmission: "Manual",
    fuel: "Diesel",
    seats: 5,
    rating: 4.7,
    reviews: 22,
    distance: 7.1,
    location: "Karol Bagh, New Delhi, Delhi, 110005, India",
    price: 3800,
    baseDeliveryFee: 350,
    deliveryPerKm: 19,
    features: ["AC", "Power Steering", "Power Windows", "Central Locking"],
    images: [
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
    ],
  },
  {
    id: 4,
    name: "Maruti Swift",
    year: 2022,
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    rating: 4.5,
    reviews: 18,
    distance: 3.5,
    location: "Rajouri Garden, New Delhi, Delhi, 110027, India",
    price: 2800,
    baseDeliveryFee: 350,
    deliveryPerKm: 19,
    features: ["Bluetooth", "AC", "Power Windows", "Push Start"],
    images: [
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
      "/api/placeholder/600/400",
    ],
  },
];

export default CarList;
